services:
  java-year:
    build: ./java-year
    ports:
      - "6001:6001"
    env_file:
      - ../env
    environment:
      - OTEL_SERVICE_NAME=java-year-$NAME

  java-name:
    build: ./java-name
    ports:
      - "6002:6002"
    depends_on:
      - java-year
    env_file:
      - ../env
    environment:
      - OTEL_SERVICE_NAME=java-name-$NAME
